import initAnimacaoScroll from "./modules/scroll-animacao.js";
import initScrollSuave from "./modules/scroll-suave.js";
import initTabNav from "./modules/tabnav.js";
import initAccordionList from "./modules/accordion.js";
import activeModal from "./modules/modal.js";
import initTooltip from "./modules/tooltip.js";
import initDropdownMenu from "./modules/dropdown-menu.js";
import initMenuMobile from "./modules/menu-mobile.js";
import InitFuncionamento from "./modules/funcionamento.js";
import initFetchAnimais from "./modules/fetch-animais.js";
import initFetchBitcoin from "./modules/fetch-bitcoin.js";

initAnimacaoScroll();
initScrollSuave();
initTabNav();
initAccordionList();
activeModal();
initTooltip();
initDropdownMenu();
initMenuMobile();
InitFuncionamento();
initFetchAnimais();
initFetchBitcoin();
